source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'puma'
gem 'json'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov'
  gem 'simplecov-cobertura'
  gem 'rubocop', require: false
  gem 'brakeman', require: false
end
